//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class android_update
    {
        public int id { get; set; }
        public string update_intro { get; set; }
        public string version_no { get; set; }
        public string update_url { get; set; }
        public long create_time { get; set; }
        public int version_id { get; set; }
    }
}
