//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_type
    {
        public int id { get; set; }
        public int cf_id { get; set; }
        public string cf_type_name { get; set; }
        public Nullable<decimal> cf_price { get; set; }
        public Nullable<int> cf_cftype { get; set; }
        public Nullable<int> cf_amount { get; set; }
        public string cf_desc { get; set; }
        public int left_amount { get; set; }
    }
}
