//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class crowd_funding
    {
        public int id { get; set; }
        public string cf_name { get; set; }
        public Nullable<int> cf_category { get; set; }
        public Nullable<int> cf_second_category { get; set; }
        public Nullable<int> cf_third_category { get; set; }
        public decimal cf_fund_end { get; set; }
        public decimal cf_fund_amount { get; set; }
        public Nullable<long> cf_begin_time { get; set; }
        public Nullable<long> cf_end_time { get; set; }
        public string cf_front_icon { get; set; }
        public string cf_video_thumbnail { get; set; }
        public Nullable<int> cf_front_icon_type { get; set; }
        public string cf_desc { get; set; }
        public string cf_note { get; set; }
        public Nullable<long> cf_created_time { get; set; }
        public Nullable<int> cf_owner_id { get; set; }
        public Nullable<int> cf_province_id { get; set; }
        public Nullable<int> cf_city_id { get; set; }
        public string cf_service_address { get; set; }
        public Nullable<long> cf_service_time { get; set; }
        public Nullable<int> cf_service_duration { get; set; }
        public Nullable<int> cf_state { get; set; }
        public int support_amount { get; set; }
        public int click_count { get; set; }
        public int fav_count { get; set; }
        public int order_count { get; set; }
    }
}
