//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string order_code { get; set; }
        public int order_source { get; set; }
        public string buyer_id { get; set; }
        public string buyer { get; set; }
        public int seller_id { get; set; }
        public string seller { get; set; }
        public int order_type { get; set; }
        public string product_name { get; set; }
        public string product_code { get; set; }
        public Nullable<long> service_time { get; set; }
        public string service_location { get; set; }
        public Nullable<long> create_time { get; set; }
        public Nullable<long> receive_time { get; set; }
        public Nullable<long> audit_time { get; set; }
        public string auditer { get; set; }
        public int status { get; set; }
        public int paystatus { get; set; }
        public decimal public_price { get; set; }
        public decimal price { get; set; }
        public Nullable<int> pay_order_type { get; set; }
        public string pay_order_id { get; set; }
        public string merchant_code { get; set; }
        public Nullable<long> pay_time { get; set; }
        public string buyer_info { get; set; }
        public int order_type_id { get; set; }
        public int order_type_sub { get; set; }
        public int amount { get; set; }
        public string order_img { get; set; }
        public Nullable<long> service_endtime { get; set; }
    }
}
