//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_detail
    {
        public int id { get; set; }
        public int user_uid { get; set; }
        public string user_icon { get; set; }
        public Nullable<int> user_city_id { get; set; }
        public Nullable<System.DateTime> user_birth { get; set; }
        public string user_career { get; set; }
        public string user_intro { get; set; }
        public string user_fronticon { get; set; }
        public Nullable<int> user_gender { get; set; }
        public string user_video { get; set; }
        public Nullable<int> click_count { get; set; }
    }
}
