//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_base
    {
        public int user_uid { get; set; }
        public Nullable<int> is_actor { get; set; }
        public string user_nick { get; set; }
        public string user_email { get; set; }
        public string user_pwd { get; set; }
        public int status { get; set; }
        public string phone { get; set; }
        public long reg_time { get; set; }
    }
}
