//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YihuiMgr.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class video_info
    {
        public int id { get; set; }
        public string v_title { get; set; }
        public string v_front_icon { get; set; }
        public string v_video_url { get; set; }
        public string v_brief { get; set; }
        public string v_detail_intro { get; set; }
        public Nullable<int> v_duration { get; set; }
        public Nullable<int> v_category { get; set; }
        public Nullable<int> v_second_category { get; set; }
        public Nullable<int> v_third_category { get; set; }
        public long v_create_time { get; set; }
        public Nullable<int> click_count { get; set; }
    }
}
